spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://postgres-order:5432/order_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    serialization:
      indent-output: true

# Configuración de clientes Feign para Docker
clients:
  product-service:
    url: http://product-service:8081

